import type { MatchConfigurationAbility, PhysicalAttackCheck } from "./types";

const physicalChecks: readonly PhysicalAttackCheck[] = [
  "range",
  "line-of-sight",
  "legal-bottle-contact",
  "terrain-contact",
];

const attackManualChecks: readonly PhysicalAttackCheck[] = physicalChecks;

export const abilities = [
  {
    id: "drow-rogue-backstab",
    name: "Backstab",
    ownerCharacterId: "drow-rogue",
    actionType: "standard",
    attackType: "Melee",
    interaction: "physical-attack",
    targetPolicy: {
      relation: "any",
      cardinality: "self",
      lifeState: "active",
    },
    range: "2 paces",
    lineOfSight: "Yes",
    ballRequired: "Yes",
    rulesText:
      "Make one physical throw. Each legal bottle physically hit takes 1 damage. Each character hit cannot use a Powerful Ability on its next turn. The effect applies to allies and enemies alike.",
    duration: "Until the end of each affected character’s next turn.",
    manualChecks: attackManualChecks,
    operations: ["deal-damage", "prohibit-action-type"],
  },
  {
    id: "drow-rogue-vanish",
    name: "Vanish",
    ownerCharacterId: "drow-rogue",
    actionType: "powerful",
    attackType: "None",
    interaction: "self",
    targetPolicy: {
      relation: "self",
      cardinality: "self",
      lifeState: "active",
    },
    range: "Self",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "Move the Rogue and bottle up to twice the Rogue’s current Move allowance plus 2 paces as part of the ability. Until the beginning of the Rogue’s next turn, the Rogue cannot be affected by physically thrown balls. Vanish does not protect against non-physical Ability Attacks.",
    duration: "Until the beginning of the Rogue’s next turn.",
    manualChecks: [],
    operations: ["manual-movement-instruction"],
  },
  {
    id: "drow-druid-shapeshift",
    name: "Shapeshift",
    ownerCharacterId: "drow-druid",
    actionType: "standard",
    attackType: "None",
    interaction: "self",
    targetPolicy: {
      relation: "self",
      cardinality: "self",
      lifeState: "active",
    },
    range: "Self",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "The Druid transforms into a beast. Its maximum HP becomes 4 instead of 3, then it restores 1 HP. Shapeshift may be activated while the Druid is active at 2 or 3 HP: at 2 HP it becomes 3/4 HP; at 3 HP it becomes 4/4 HP. While Shapeshifted, healing may restore the Druid up to 4 HP. If damage reduces the Druid below 3 HP, Shapeshift ends immediately and its maximum HP returns to 3. Healing back to 3 HP after Shapeshift ends does not reactivate the spent ability.",
    duration:
      "Until damage reduces the Druid below 3 HP or the Druid becomes Downed.",
    manualChecks: [],
    operations: ["heal", "change-max-hp"],
  },
  {
    id: "drow-druid-nature-s-renewal",
    name: "Nature’s Renewal",
    ownerCharacterId: "drow-druid",
    actionType: "standard",
    attackType: "None",
    interaction: "ally",
    targetPolicy: { relation: "ally", cardinality: "one", lifeState: "active" },
    range: "4 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "The target restores 1 HP, up to that character’s current maximum HP. A character at full HP or a Downed character cannot be targeted.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["heal"],
  },
  {
    id: "drow-paladin-lay-on-hands",
    name: "Lay on Hands",
    ownerCharacterId: "drow-paladin",
    actionType: "standard",
    attackType: "None",
    interaction: "ally",
    targetPolicy: { relation: "ally", cardinality: "one", lifeState: "either" },
    range: "3 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "Choose one: restore 1 HP to a living target, up to that character’s maximum HP; or restore a Downed ally to 1 HP and stand their bottle upright. A living character at full HP cannot be targeted. A revived character returns to its original initiative position: if that position is still ahead this round, it acts normally when reached; if it has already passed, it waits until the next round. Revival grants no immediate extra turn and does not restore spent abilities or previous temporary effects.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["heal", "revive"],
  },
  {
    id: "drow-paladin-divine-shield",
    name: "Divine Shield",
    ownerCharacterId: "drow-paladin",
    actionType: "reaction",
    attackType: "None",
    interaction: "ally",
    targetPolicy: { relation: "ally", cardinality: "one", lifeState: "active" },
    range: "3 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "When an attack would affect the chosen character, reduce that character's remaining damage by 1. The legal hit and its attached effects still resolve; the same attack may still affect other characters normally.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["reduce-remaining-damage"],
  },
  {
    id: "drow-wizard-frostbind",
    name: "Frostbind",
    ownerCharacterId: "drow-wizard",
    actionType: "standard",
    attackType: "None",
    interaction: "enemy",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "6 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "On the target’s next turn, its movement is limited to a maximum of 1 pace. This restriction also limits movement granted by abilities unless that ability explicitly overrides movement restrictions. The target may still take its Major Action normally.",
    duration: "The target’s next turn.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["set-movement-cap"],
  },
  {
    id: "drow-wizard-misty-escape",
    name: "Misty Escape",
    ownerCharacterId: "drow-wizard",
    actionType: "reaction",
    attackType: "None",
    interaction: "self",
    targetPolicy: {
      relation: "self",
      cardinality: "self",
      lifeState: "active",
    },
    range: "Self",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "When an attack would affect the Wizard, use Attack Avoidance to prevent all damage and effects from that attack against the Wizard. The Wizard may then immediately move up to 2 paces. This is ability-granted movement and does not consume the Wizard’s next turn movement, but existing movement restrictions still apply unless explicitly overridden.",
    duration: "Immediate.",
    manualChecks: [],
    operations: ["prevent-damage-and-effects", "manual-movement-instruction"],
  },
  {
    id: "drow-sorcerer-arcane-bolt",
    name: "Arcane Bolt",
    ownerCharacterId: "drow-sorcerer",
    actionType: "standard",
    attackType: "Ability Attack",
    interaction: "targeted-attack",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "6 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "The target takes 1 damage automatically. No accuracy throw is made. Physical cover does not prevent the damage, but bottle-to-bottle Line of Sight is still required. Legal Reactions may prevent or modify the attack.",
    duration: "Immediate.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["deal-damage"],
  },
  {
    id: "drow-sorcerer-mirror-veil",
    name: "Mirror Veil",
    ownerCharacterId: "drow-sorcerer",
    actionType: "reaction",
    attackType: "None",
    interaction: "self",
    targetPolicy: {
      relation: "self",
      cardinality: "self",
      lifeState: "active",
    },
    range: "Self",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "When an attack would affect the Sorcerer, use Attack Avoidance to prevent all damage and effects from that attack against the Sorcerer. The attack may still affect other characters normally.",
    duration: "Immediate.",
    manualChecks: [],
    operations: ["prevent-damage-and-effects"],
  },
  {
    id: "drow-bard-inspiring-words",
    name: "Inspiring Words",
    ownerCharacterId: "drow-bard",
    actionType: "standard",
    attackType: "None",
    interaction: "ally",
    targetPolicy: { relation: "ally", cardinality: "one", lifeState: "active" },
    range: "4 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "The target restores 1 HP, up to that character’s maximum HP. A character at full HP or a Downed character cannot be targeted.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["heal"],
  },
  {
    id: "drow-bard-battle-hymn",
    name: "Battle Hymn",
    ownerCharacterId: "drow-bard",
    actionType: "powerful",
    attackType: "None",
    interaction: "ally",
    targetPolicy: {
      relation: "ally",
      cardinality: "all-in-range",
      lifeState: "active",
    },
    range: "4 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "At activation, every living Drow ally within 4 paces, including the Bard, receives +1 Move for the rest of the Match unless that character becomes Downed. This does not grant an extra action. Characters who later enter the radius do not gain the buff. A Downed character loses this bonus and Revival does not restore it. If a movement restriction applies, the more restrictive allowance wins.",
    duration: "Until the recipient becomes Downed.",
    manualChecks: ["range"],
    operations: ["set-movement-cap"],
  },
  {
    id: "duergar-ranger-hunter-s-mark",
    name: "Hunter’s Mark",
    ownerCharacterId: "duergar-ranger",
    actionType: "standard",
    attackType: "None",
    interaction: "enemy",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "6 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "Mark the target. The first successful damaging attack against the marked character deals +1 damage. The Mark is then consumed. If the qualifying attack is reduced to 0 damage, the Mark is not consumed.",
    duration:
      "Until triggered or until the end of the Ranger’s next scheduled initiative position, whichever comes first. This expiry occurs even if the Ranger is Downed and skipped. Ends immediately if the affected character is Downed.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["add-damage"],
  },
  {
    id: "duergar-ranger-deadeye",
    name: "Deadeye",
    ownerCharacterId: "duergar-ranger",
    actionType: "standard",
    attackType: "Ability Attack",
    interaction: "targeted-attack",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "8 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "The target takes 1 damage automatically. No accuracy throw is made. Physical cover does not prevent the damage, but bottle-to-bottle Line of Sight is still required. Legal Reactions may prevent or modify the attack.",
    duration: "Immediate.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["deal-damage"],
  },
  {
    id: "duergar-monk-stunning-strike",
    name: "Stunning Strike",
    ownerCharacterId: "duergar-monk",
    actionType: "standard",
    attackType: "Melee",
    interaction: "physical-attack",
    targetPolicy: { relation: "any", cardinality: "self", lifeState: "active" },
    range: "2 paces",
    lineOfSight: "Yes",
    ballRequired: "Yes",
    rulesText:
      "Make one physical throw. Each legal bottle physically hit takes 1 damage. Each character hit cannot use a Powerful Ability on its next turn.",
    duration: "Until the end of each affected character’s next turn.",
    manualChecks: attackManualChecks,
    operations: ["deal-damage", "prohibit-action-type"],
  },
  {
    id: "duergar-monk-deflecting-palm",
    name: "Deflecting Palm",
    ownerCharacterId: "duergar-monk",
    actionType: "reaction",
    attackType: "None",
    interaction: "self",
    targetPolicy: {
      relation: "self",
      cardinality: "self",
      lifeState: "active",
    },
    range: "Self",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "When a physical ball hits the Monk, use Attack Avoidance to prevent all damage and effects from that attack against the Monk. The same ball is immediately redirected toward the original thrower’s current bottle position. It remains the same attack: all attached ball effects remain attached, each bottle may still be affected at most once, and the attack keeps its original source and hard maximum range.",
    duration: "Immediate.",
    manualChecks: [],
    operations: ["prevent-damage-and-effects", "redirect-physical-attack"],
  },
  {
    id: "duergar-fighter-hold-the-line",
    name: "Hold the Line",
    ownerCharacterId: "duergar-fighter",
    actionType: "powerful",
    attackType: "None",
    interaction: "ally",
    targetPolicy: {
      relation: "ally",
      cardinality: "all-in-range",
      lifeState: "active",
    },
    range: "2 paces",
    lineOfSight: "N/A",
    ballRequired: "No",
    rulesText:
      "At activation, the Fighter and every living Duergar ally within 2 paces receives protection. Until the beginning of the Fighter’s next turn, the first attack against each recipient that would still deal at least 1 damage reduces its remaining damage by 1. The legal hit and attached effects still resolve. Recipients are fixed at activation; later entrants do not receive protection. Protection ends separately when a recipient becomes Downed and Revival does not restore it.",
    duration: "Until the beginning of the Fighter’s next turn or until used.",
    manualChecks: ["range"],
    operations: ["reduce-remaining-damage"],
  },
  {
    id: "duergar-fighter-shield-wall",
    name: "Shield Wall",
    ownerCharacterId: "duergar-fighter",
    actionType: "reaction",
    attackType: "None",
    interaction: "ally",
    targetPolicy: { relation: "ally", cardinality: "one", lifeState: "active" },
    range: "2 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "When an attack affects the chosen character, reduce that character's remaining damage by 1. The legal hit and its attached effects still resolve. Other characters affected by the same attack resolve normally.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["reduce-remaining-damage"],
  },
  {
    id: "duergar-barbarian-brutal-shove",
    name: "Brutal Shove",
    ownerCharacterId: "duergar-barbarian",
    actionType: "standard",
    attackType: "Melee",
    interaction: "physical-attack",
    targetPolicy: { relation: "any", cardinality: "self", lifeState: "active" },
    range: "2 paces",
    lineOfSight: "Yes",
    ballRequired: "Yes",
    rulesText:
      "Make one physical throw. Each legal bottle hit takes 1 damage and is forced up to 2 paces directly away from the Barbarian, stopping at the furthest legal position. After Reactions are resolved, apply the forced movement before checking whether Brutal Shove’s finalized damage Downs that character; if it reaches 0 HP, lay the bottle flat at its new position. Forced movement does not consume the target’s normal movement and is not modified by movement bonuses or restrictions. Bottles may not overlap or leave the battlefield. An already-Downed bottle is never moved by Brutal Shove.",
    duration: "Immediate.",
    manualChecks: attackManualChecks,
    operations: ["deal-damage", "manual-movement-instruction"],
  },
  {
    id: "duergar-barbarian-rampage",
    name: "Rampage",
    ownerCharacterId: "duergar-barbarian",
    actionType: "powerful",
    attackType: "Melee",
    interaction: "physical-attack",
    targetPolicy: { relation: "any", cardinality: "self", lifeState: "active" },
    range: "2 paces",
    lineOfSight: "Yes",
    ballRequired: "Yes",
    rulesText:
      "Move the Barbarian up to twice its current Move allowance, then make one physical melee throw from the new position. Each legal bottle hit takes 1 damage and is pushed up to 2 paces directly away from the Barbarian under the Brutal Shove movement rules. A Rampage with no legal bottle hit remains valid and spent. Movement restrictions and bonuses affect the movement allowance.",
    duration: "Immediate.",
    manualChecks: attackManualChecks,
    operations: ["deal-damage", "manual-movement-instruction"],
  },
  {
    id: "duergar-warlock-hex",
    name: "Hex",
    ownerCharacterId: "duergar-warlock",
    actionType: "standard",
    attackType: "None",
    interaction: "enemy",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "6 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "Hex the target. The first successful damaging attack against the Hexed character deals +1 damage. If that attack finalizes at 1 or more damage, Hex is consumed and the target’s movement on its next turn is limited to a maximum of 1 pace. If the qualifying attack is reduced to 0 damage, Hex is not triggered or consumed.",
    duration:
      "Pending Hex lasts until triggered or until the end of the Warlock’s next scheduled initiative position, whichever comes first; this expiry occurs even if the Warlock is Downed and skipped. After Hex triggers, the resulting 1-pace restriction lasts through the affected character’s next turn. If the affected character becomes Downed, both a pending Hex and any resulting movement restriction end immediately.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["add-damage", "set-movement-cap"],
  },
  {
    id: "duergar-warlock-eldritch-blast",
    name: "Eldritch Blast",
    ownerCharacterId: "duergar-warlock",
    actionType: "standard",
    attackType: "Ability Attack",
    interaction: "targeted-attack",
    targetPolicy: {
      relation: "enemy",
      cardinality: "one",
      lifeState: "active",
    },
    range: "6 paces",
    lineOfSight: "Yes",
    ballRequired: "No",
    rulesText:
      "The target takes 1 damage automatically. No accuracy throw is made. Physical cover does not prevent the damage, but bottle-to-bottle Line of Sight is still required. Legal Reactions may prevent or modify the attack.",
    duration: "Immediate.",
    manualChecks: ["range", "line-of-sight"],
    operations: ["deal-damage"],
  },
  {
    id: "duergar-cleric-blessing-of-battle",
    name: "Blessing of Battle",
    ownerCharacterId: "duergar-cleric",
    actionType: "standard",
    attackType: "None",
    interaction: "ally",
    targetPolicy: {
      relation: "ally",
      cardinality: "one",
      lifeState: "active",
    },
    range: "4 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "The target receives +1 Move for the rest of the Match unless the target becomes Downed. If a movement restriction applies, the more restrictive allowance wins. Revival does not restore this bonus.",
    duration: "Until the recipient becomes Downed.",
    manualChecks: ["range"],
    operations: ["set-movement-cap"],
  },
  {
    id: "duergar-cleric-revivify",
    name: "Revivify",
    ownerCharacterId: "duergar-cleric",
    actionType: "standard",
    attackType: "None",
    interaction: "ally",
    targetPolicy: {
      relation: "ally",
      cardinality: "one",
      lifeState: "downed",
    },
    range: "3 paces",
    lineOfSight: "No",
    ballRequired: "No",
    rulesText:
      "Restore the target to 1 HP and stand their bottle upright. The revived character returns to its original initiative position: if that position is still ahead this round, it acts normally when reached; if it has already passed, it waits until the next round. Revival grants no immediate extra turn and does not restore spent abilities or previous temporary effects. Revivify cannot restore a character whose team has already been permanently eliminated.",
    duration: "Immediate.",
    manualChecks: ["range"],
    operations: ["revive"],
  },
] as const satisfies readonly MatchConfigurationAbility[];
